config/routes.rb
Rails.application.routes.draw do
  resources :products

  get 'users/index'
  devise_for :users
  resources :users
  resources :clients

  post 'users/update_roles', to: 'users#update_roles', as: 'update_roles'

  patch 'export', to: 'products#export_csv', as: 'export_products'

  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # resources :invoices, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :user

  has_many :products, dependent: :destroy

end

app/models/product.rb
class Product < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search_all, 
    against: [:name, :etat], 
    associated_against: {
      client: [:lastname]
    },
    using: { tsearch: { prefix: true } }
  
  belongs_to :client

  ETATPRODUCT = ["neuf", "occasion", "reconditionné"]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :clients, dependent: :destroy

  def fullname 
    self.firstname + " " + self.lastname 
  end


  include PgSearch::Model
  pg_search_scope :search_all, against: [:firstname, :lastname], using: { tsearch: { prefix: true } }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_client, only: [:edit, :update, :destroy]

  def index
    @clients = Client.all
   
  end

  def new
    @client = Client.new
    @users = User.all
  end

  def edit
    @users = User.all
  end

  def update
    if @client.update(client_params)
      redirect_to clients_path, notice: 'clients was successfully updated.'
    else
      render :new
    end
  end

  def create
    @client = Client.new(client_params)
    if @client.save!
      redirect_to clients_path, notice:  'Client was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @client.destroy
    redirect_to clients_path, notice: 'client was successfully destroyed.'
  end

private
  def set_client
    @client = Client.find(params[:id])
  end
  def client_params
     params.require(:client).permit(:username, :lastname, :phone, :mail, :comment, :actif, :user_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/products_controller.rb
require 'csv'

class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    if params[:search] && !params[:search].empty?
      @products = Product.search_all(params[:search])
    else
      @products = Product.all
    end

    respond_to do |format|
      format.html
      format.json
    end
  end

  # GET /products/1 or /products/1.json
  def show
  end

  def export_csv
    @products = Product.all

    respond_to do |format|
      format.csv { send_data generate_csv(@products), filename: "products.csv" }
    end
  end

  # GET /products/new
  def new
    @product = Product.new
    @product.deliveryDate = Date.today
    @clients = Client.all
  end

  # GET /products/1/edit
  def edit
    @clients = Client.all
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :number, :client_id, :etat, :deliveryDate, :onSite)
    end

    def generate_csv(products)
      CSV.generate(headers: true) do |csv|
        csv << ["Name", "Number"] # Ajoute les en-têtes des colonnes
  
        products.each do |product|
          csv << [product.name, product.number] # Ajoute les données de chaque produit
        end
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :set_users, only: [:edit, :update, :destroy]

  def index
    if params[:search] && !params[:search].empty?
      @users = User.search_all(params[:search])
    else
      @users = User.all
    end
   
  end

  def update_roles
    User.update_all(role: 'admin')
    redirect_to users_path, notice: 'Tous les utilisateurs sont maintenant des administrateurs.'
  end

  def new
    @users = User.new
  end

  def edit
  end

  def update
    if @users.update(users_params)
      redirect_to users_path, notice: 'users was successfully updated.'
    else
      render :new
    end
  end

  def create
    @users = User.new(users_params)
    @users.user_id = current_user.id
    if @users.save!
      redirect_to users_path, notice:  'User was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @users.destroy
    authorize @users
    redirect_to users_path, notice: 'user was successfully destroyed.'
  end

private
  def set_users
    @users = User.find(params[:id])
  end
  def users_params
     params.require(:user).permit(:email, :firstname, :lastname, :tel, :role)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/clients/_form.html.erb
<%= simple_form_for(@client) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :username, input_html: { class: "style-input" } %>
    <%= f.input :lastname, input_html: { class: "style-input" } %>
    <%= f.input :comment, input_html: { class: "style-input" } %>
    <%= f.association :user, collection: @users,
    :label_method => :lastname,
    :value_method => :id,
    :label => "Utilisateur" 
    %>

  <br>
    <div class="form-actions">
      <%= f.button :submit, class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1 class="center">Edit client</h1>

<%= render 'form', user: @client %>
<br>
<div class="right" >
  <%= link_to '', client_path, class: "fas fa-arrow-left btn btn-outline-secondary" %>
</div>

app/views/clients/index.html.erb
<h1>Liste des clients</h1>
<%= link_to ' New', new_client_path, class: "fa fa-plus btn btn-success"%>
  <div class="card-body">
    <% l = 0 %>
      <table class="table table-hover">
          <thead  class="thead-dark">
            <tr>
                <th scope="row" colspan="1">username</th>
                <th scope="row" colspan="1">Lastname</th>
                <th scope="row" colspan="1">user</th>
                <th colspan="1">role</th>
            </tr>
          </thead>
        <% @clients.each do |client| %>
            <tbody >
                <tr>
                  <td><%= client.username %></td>
                  <td><%= client.lastname %></td>
                  <td><%= client.user.fullname %> </td>
                  <td class="taches">
                    <div class="d-flex">
                      <%= link_to '', edit_client_path(client), class: "btn fa fa-pen tdhidden" %>
                      <%= button_to '', client, method: :delete, :onclick => "return confirm('Are you sure you want to delete?')", class: "btn text-danger fa fa-trash tdhidden" %>
                    </div>
                  </td>
                </tr>
            </tbody>
        <% end %>
      </table>
  </div>


<%= link_to " Back", :back , class: "fas fa-arrow-left btn btn-outline-secondary"%>

app/views/clients/new.html.erb
<%= render 'form', user: @client %>

app/views/clients/show.html.erb
<h1>Clients#show</h1>
<p>Find me in app/views/clients/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Webpack</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body><%= render "shared/navbar" %>
    
    <%= render "shared/flashes" %>
    <div class="container p-2">
      <%= yield %>
    </div>
  </body>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
</html>

app/views/pages/home.html.erb
<div class="row justify-content-center">
  <div class="col-sm-8 text-center">
      <h3>Gestion des dossier</h3>
    <div class="d-flex flex-wrap justify-content-center pt-4">
        <a href="/users">
            <div class="card-home">
            <div>
                <h3 class="fas fa-user"></h3>
                <h3>Users</h3>
            </div>
            </div>
        </a>
        <%= link_to  users_path() do %>
        <div class="card-home">
            <div>
                <h3 class="fas fa-user"></h3>
                <h3>Users</h3>
            </div>
            </div>
        <%end%> 

        <%= link_to  clients_path() do %>
        <div class="card-home">
            <div>
                <h3 class="fas fa-user"></h3>
                <h3>Clients</h3>
            </div>
            </div>
        <%end%> 
        <%= link_to  products_path() do %>
        <div class="card-home">
            <div>
                <h3 class="fas fa-user"></h3>
                <h3>Products</h3>
            </div>
            </div>
        <%end%> 
    </div>


<div>

<%= link_to "Back", :back %>

app/views/products/_form.html.erb
<%= simple_form_for(@product) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :number %>
    <%= f.input :etat, as: :radio_buttons, collection: Product::ETATPRODUCT, checked: @product.etat || Product::ETATPRODUCT.first %>
    <%= f.input :deliveryDate, as: :date, html5: true %>
    <%= f.input :onSite %>
    <%= f.association :client, collection: @clients,
    :label_method => :lastname,
    :value_method => :id,
    :label => "Client" 
    %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <h3>
    <%= product.name %>
  </h3>

  <p>
    <strong>Number:</strong>
    <%= product.number %>
    </p>
    <strong>Etat:</strong>
    <%= product.etat %>
    </p>
    <p><strong>Date livraison:</strong>
    <%= product.deliveryDate %>
    </p>
    <p>
    <strong>Sur site:</strong>
    <%= product.onSite %>
  </p>

  <p>
    <strong>Client:</strong>
    <%= product.client.username %>
  </p>

    <p>
      <%= link_to "Show this product", product %>
    </p>
  <%= button_to "Supprimer", product, method: :delete %>

</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Products</h1>

<%= button_to 'Extraction', export_products_path(format: :csv), method: :patch, class: "fa fa-plus btn btn-success"%>
<%= button_to 'Extraction json', products_path(format: :json), method: :get, class: "fa fa-plus btn btn-success"%>

<div class="mt-4">
  <%= form_tag products_path, method: :get, class: "form-inline justify-content-center" do %>
    <%= text_field_tag :search, params[:search], class: "form-control mr-2", placeholder: "Search" %>
    <%= submit_tag "Search", class: "btn btn-primary" %>
  <% end %>
</div>
<br>

<div id="products" style="display:flex;">
  <% @products.each do |product| %>
  <div style="display:flex; flex-direction:column; margin: 20px; border: solid 1px; padding: 5px; border-radius:3px">
    <%= render product %>
  </div>
  <% end %>
</div>

<%= link_to "New product", new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<div>
  <%= link_to "Edit this product", edit_product_path(@product) %> |
  <%= link_to "Back to products", products_path %>

  <%= button_to "Destroy this product", @product, method: :delete %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar1">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          

          <li class="nav-item dropdown">
          <%=current_user.lastname %>
            <%= image_tag "user.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_searchbar.html.erb
  <%= form_tag search_path, method: :get, class: "form-inline justify-content-center" do %>
    <%= text_field_tag :search, params[:search], class: "form-control mr-2", placeholder: "Search" %>
    <%= submit_tag "Search", class: "btn btn-primary" %>
  <% end %>

app/views/users/_form.html.erb
<%= simple_form_for(@users) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :email, input_html: { class: "style-input" } %>

  <br>
    <div class="form-actions">
      <%= f.button :submit, class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1 class="center">Edit user</h1>

<%= render 'form', user: @user %>
<br>
<div class="right" >
  <%= link_to '', users_path, class: "fas fa-arrow-left btn btn-outline-secondary" %>
</div>

app/views/users/index.html.erb
<h1>Liste des utilisateurs</h1>
<%= link_to ' New', new_user_path, class: "fa fa-plus btn btn-success"%>
<%= render "shared/searchbar", search_path: users_path%>
  <div class="card-body">
    <% l = 0 %>
      <table class="table table-hover">
          <thead  class="thead-dark">
            <tr>
                <th scope="row" colspan="1">email</th>
                <th scope="row" colspan="1">Fistname</th>
                <th scope="row" colspan="1">Lastname</th>
                <th scope="row" colspan="1">tel</th>
                <th scope="row" colspan="1">Liste des clients</th>
                <th colspan="1">role</th>
            </tr>
          </thead>
        <% @users.each do |user| %>
            <tbody >
                <tr>
                  <td scope="row"><%= user.email %></td>
                  <td><%= user.firstname %></td>
                  <td><%= user.lastname %></td>
                  <td><%= user.tel %></td>
                  <td><% user.clients.each do |client| %>
                  <li><%= client.username %></li>
                  <% end %>
                  <td><%= user.role %></td>
                  <td class="taches">
                    <div class="d-flex">
                      <%= link_to '', edit_user_path(user), class: "btn fa fa-pen tdhidden" %>
                      <%= button_to '', user, method: :delete, :onclick => "return confirm('Are you sure you want to delete?')", class: "btn text-danger fa fa-trash tdhidden" %>
                    </div>
                  </td>
                </tr>
            </tbody>
        <% end %>
      </table>
  </div>

<%= button_to ' Admn', update_roles_path, method: :post, class: "fa fa-plus btn btn-success"%>



<%= link_to " Back", :back , class: "fas fa-arrow-left btn btn-outline-secondary"%>

app/views/users/new.html.erb
<h1 class="center">Nouveau user </h1>

<%= render 'form', user: @user %>

<div class="right">
  <%= link_to ' Retour', users_path, class: "fas fa-arrow-left" %>
</div>